- name: "Setup HTPassword authentication"
  hosts: masters
  remote_user: root
  vars:
    users:
      user1:
        name: admin
        pass: admin1
      user2:
        name: developer
        pass: developer
  handlers:
    - name: 'restart origin-master-api'
      service:
        name: origin-master-api
        state: restarted
  tasks:
    - name: "Install httpd-tools package"
      yum:
        name: httpd-tools

    - name: "Install python-passlib package"
      yum:
        name: python-passlib

    - name: "Enable HTPassword identity provider in master configuration"
      replace:
        path: /etc/origin/master/master-config.yaml
        regexp: '(Allow|Deny)AllPasswordIdentityProvider'
        replace: 'HTPasswdPasswordIdentityProvider'
        after: 'identityProviders'
      notify: 'restart origin-master-api'

    - name: "Create passwd file"
      file:
        path: '/etc/origin/openshift-passwd'
        state: file

    - name: "Configure path to passwd file"
      lineinfile: 
        path: /etc/origin/master/master-config.yaml
        insertafter: 'HTPasswdPasswordIdentityProvider'
        line: '      file: /etc/origin/openshift-passwd'
      notify: 'restart origin-master-api'

    - name: "Create users and passwords"
      htpasswd:
        path: '/etc/origin/openshift-passwd'
        name: "{{ user.value.name }}"
        password: "{{ user.value.pass }}"
      with_dict: "{{ users }}"
      loop_control:
        loop_var: user
